daily_work_homepage:
    path:     /
    defaults: { _controller: DailyWorkBundle:Default:index }
    
daily_work:
    path:    /dw
    defaults: { _controller: DailyWorkBundle:Default:daily_work }

consulta_page:
    path: /{id_paciente}
    defaults: { _controller: DailyWorkBundle:Default:consulta }
